---
title: "Does your birthday make you better at sports?"
subtitle: "Case Study 5"
author: "Kyle Tolliver"
---

```{r load_libraries, include=FALSE}
library(tidyverse)
```

## Background

Matthew 25:29 explains that _‘whoever has will be given more, and they will have an abundance. Whoever does not have, even what they have will be taken from them’ _which has lead many researchers to describe how some get more and others get less as the‘Matthew Effect’ in our society.

One way to evaluate this effect is to look at professional athletes. Malcolm Gladwell studies the birth dates of successful hockey players in a chapter of his 2008 non-fiction book Outliers to provide an example of the Matthew Effect. Please read the Matthew Effect chapter to get more background.

Hockey’s cutoff date is December 31st, but baseball’s cutoff date has historically been July 31st. Football’s cutoff is July 31st as well but they also have weight categories as well for older ages. Basketball’s AAU cutoff date is August 31st.

### Challenge

Malcolm Gladwell’s chapter on the Matthew Effect is persuasive as a narrative. He even has a couple of tables. After reading his Matthew Effect chapter, your job is to create a few persuasive visualizations about the birthday distributions within each sport. In addition, you will need to compare the sport birthday distributions to the distributions of birthdays in the US population to verify that the population of birthdays is in fact different.

## Deliverables

* Build a [6-10 slide presentation](./analysis/cs5.pptx) that provides data visualizations to pair up with text from Malcolm Gladwell’s chapter on the Matthew Effect.
  + At least one slide should have a visualization that compares the US population of births to a sport of your preference with persuasive annotations added to the graphics.
  + At least three slides should describe and show the [statistical comparison](./analysis/cs5.xlsx) you performed to provide justification for your inference.
  + Your final slide should have your conclusions beyond the observed data.

--- Visualizations created using [Tableau](./tableau/CS5.twb)  

## Class Meeting

### Objective 

Students discover how to move their visualizations and data beyond descriptions to make inferential statements using statistics. They will be introduced to how to compare proportion estimates from two groups to see if they are different (test of two proportions).  In addition, they will be introduced to methods for comparing two categorical measures to test for a relationship (Chi-Square test of independence)

## Topics Covered

* Hypothesis testing and its use in statistical inference.
* How to compare two proportions to see if the populations are different.
* How to compare two categorical variables to see if there is a relationship between them.

## Readings

* The [Matthew Effect](https://byuistats.github.io/CSE150/files/matthew_effect_gladwell.pdf)

### Day 15

* Read Good Charts (Type: Visualization)
  + Chapter 8: Present to Persuade (pg. 192-208)
* Read CSE 150 Data Intuition and Insight (Type: Statistics)
  + Section 4.1: Introduction
  + Section 4.2: Hypothesis Tests 

### Day 16

* Read CSE 150 Data Intuition and Insight (Type: Statistics)
  + Section 4.3: Confidence Intervals
  + Section 4.4: Comparing Proportional Measures

### Day 17

* Read CSE 150 Data Intuition and Insight (Type: Statistics)
  + Section 4.5: Chi-Squared Test of Independence 

### Day 18

* None