---
title: "Introduction"
subtitle: "Case Study 1"
---

```{r load_libraries, include=FALSE}
library(tidyverse)
```

## Background

Data intuition and insight is not rocket science. However, there is a science to data handling, visualization, and decision making with data. The material we cover this semester will introduce to topics around this science.

### Challenge

Make sure you understand the course objectives and that you are introduced to the material and tools of the course.

## Deliverables

* Complete the quizzes for the first two days of class in [Canvas](https://byui.instructure.com/)

## Class Meeting

### Objective 

During the first two days of the semester students will get oriented with the course and begin building a foundation of software and visualization skills to complete the objectives of this course.

### Topics Covered

* The structure and objectives of CSE 150 Data Intuition and Insight.
* The technology that will be used during the course.
* The reading material that will be used during the course.

## Readings

### Day 1  

* Watch [How Humans See Data](https://www.youtube.com/watch?v=fSgEeI2Xpdc)
* Read Good Charts (Type: Visualization)
  + Introduction
  + Chapter 1: A brief history of DataViz 

### Day 2 

* Read Good Charts (Type: Visualization)
  + Chapter 2: When a chart hits our eyes
* Read CSE 150: Data Intuition and Insight
  + Section 1.1: Tidy Data (Type: Data)
  + Sections 6.1.1 and 6.1.2: Google Sheets (Type: Tools)