---
title: "Catch me, if you can?"
subtitle: "Case Study 6"
author: "Kyle Tolliver"
---

```{r load_libraries, include=FALSE}
library(tidyverse)
```

## Background

You have recently been hired by the U.S. internal revenue service (IRS) to catch corporate cheaters. You have been given three companies to investigate. You will need to decide if the IRS should build a legal case to investigate the institution for fraud.

* Sino Forest Corporation: You have the values from the financial statement numbers of Sino Forest Corporation’s 2010 Report.
* Government Entity: A dataset containing the card transactions for a government entity - 2010.
* General Motors: The amounts paid to vendors for the 90 days preceding General Motor’s 2009 liquidation.

### Challenge

You will be responsible to report as much evidence as you can with the data provided for each institution above. The government entity has more available data than the other two which will require you to dig deeper to find additional clues.

## Deliverables

* A 8-12 slide presentation to your IRS managers on the case against each entity.
* At least one slide that shows the statistical test results from the analysis you performed.
* At least one slide per institution that visualizes their first digit distribution compared to Benford’s law.
* At least one slide for one of the institutions that compares the last digit distribution to what would be expected.
* Multiple visualizations of the Government Entity data to find other interesting insights.

## Class Meeting

### Objective 

Students will come to understand the difference between visualizing a sample of data and using statistics to make inferential statements about an observed sample of data.  They will learn about a common accounting technique to find potential cheaters using the Chi-square Goodness of Fit Test.

### Topics Covered

* Hypothesis testing for a goodness of fit test.
* How to compare observed counts to an expected distribution of counts.
* The proper way to draw conclusions from statistical tests

## Readings

### Day 19

* Read [Benford’s Law (The First Digit Law): Simple Definition, Examples](https://www.statisticshowto.com/benfords-law/) (Type: Statistics)

### Day 20

* Read [Visualize Benford's Law](https://help.tableau.com/current/pro/desktop/en-us/benford.htm) (Type: Tools)

### Day 21

* Read Good Charts (Type: Visualization)
  + Chapter 9: Visual Crit

### Day 22

* Read [Call Centers and Data Requests](https://byuistats.github.io/CSE150/files/FSCPD_Donahue_callcenter.pdf) (Type: Data)