---
title: "Do you want to be a data scientist?"
subtitle: "Case Study 8"
author: "Kyle Tolliver"
---

```{r load_libraries, include=FALSE}
library(tidyverse)
```

## Background

Data scientists need to have resumes that show strong experience in solving real-world problems. While employers know that their job candidates need experience, they often don’t know what experience they need and often list too many requirements.

### Challenge

To finish the semester you will need to create your hypothetical resume that you could use upon graduation from BYU-I to a data science or analytics position. Your resume will need to combine the three elements of coursework available, the real-work experience you can accumulate over your next few years before graduation, and the job requirements of the currently available positions for undergraduate data scientists.

## Deliverables

* A one-page dream data science [resume](https://kctolli.github.io/site_libs/images/resume.html).
* A second page of sources that you used to justify the stuff in your resume.
* A cover letter that describes what you have learned from this course.

<!-- ## Teach One Another -->

<!-- ### Cases Studies -->

<!-- ## Class Meeting -->

<!-- ### Objective  -->

<!-- ## Resume  -->

<!-- [Resume](https://kctolli.github.io/site_libs/images/resume.html) -->

<!-- ### Additions -->

<!-- I would add Machine Learning to my resume. I would also add Web Backend material such as APIs and NoSQL. I would also keep the projects updated. I also would add Statistics skills and knowledge. I wish I could be able to add things like Applied Linear Regression, Big Data, and Statistical Consulting.  -->

<!-- ### Justifications  -->

<!-- #### Fall 2020 Classes -->

<!-- * MATH 325 - Intermediate Stats -->
<!-- * WDD 330 - Web Frontend 2 -->
<!-- * CSE 341 - Web Backend 2 -->
<!-- * CSE 450 - Machine Learning -->

<!-- ## What I learned in CSE 150 -->

