---
title: "Case Study 4"
subtitle: "Readings"
---

## Objective 
Students will understand how percentiles are calculated and data distribution assumptions (Normal distribution).  They will explore how to compare subjects from different normal distributions to explain performance using z-scores. Finally, they will understand the concepts of a confidence interval and how one is calculated using z-scores and normality assumptions.

### Topics Covered

* How to calculate Z-scores for comparison across varied groups.
* How to calculate percentiles from data and from normal distribution assumptions.
* How to use and interpret a confidence interval.

## Day 11

* Read Good Charts (Type: Visualization)
  + Chapter 7: Persuasion or Manipulation
* Read [Build a Line Chart](https://help.tableau.com/current/pro/desktop/en-us/buildexamples_line.htm) (Type:Tools)
* Read [Build a Box Plot](https://help.tableau.com/current/pro/desktop/en-us/buildexamples_boxplot.htm) (Types: Tools)

## Day 12

* None

## Day 13

* Read Good Charts (Type: Visualization)
  + Chapter 8: Present to Persuade (pg. 177-192)

## Day 14

* CSE 150 Data Intuition and Insight 
  + Chapter 3: Probability, Sampling, and Confidence Intervals (Type: Statistics)