---
title: "Case Study 7"
subtitle: "Readings"
---

## Objective 

Students will learn the complications that come with requesting and manipulating data for use in an analysis.  They will grasp that data scientists usually work in diverse teams that require them to be able to speak with technical staff in Information Technology (IT) and computer scientists as well as communicate and connect with management and other business consumers about data.

### Topics Covered

* Translate business questions into data requests.
* To request data from technical programmers.
* Compare and contrast R, Python, and SQL for data wrangling.

## Readings

### Day 23

* Read [How to ask for data sets](https://medium.com/@ckreibich/how-to-ask-for-datasets-d5ef791cb38c)

### Day 24

* None

### Day 25

* Read Good Charts (Type: Visualization)
  + Conclusion Chapter of Good Charts

### Day 26

* Read [Building your dream data science resume](https://www.dataquest.io/blog/how-data-science-resume-cv/)

## Class Notes