---
title: "Case Study 1"
subtitle: "Class Meeting"
---

## Objective 

During the first two days of the semester students will get oriented with the course and begin building a foundation of software and visualization skills to complete the objectives of this course.

### Topics Covered

* The structure and objectives of CSE 150 Data Intuition and Insight.
* The technology that will be used during the course.
* The reading material that will be used during the course.

## Readings

### Day 1  

* Watch [How Humans See Data](https://www.youtube.com/watch?v=fSgEeI2Xpdc)
* Read Good Charts (Type: Visualization)
  + Introduction
  + Chapter 1: A brief history of DataViz 

### Day 2 

* Read Good Charts (Type: Visualization)
  + Chapter 2: When a chart hits our eyes
* Read CSE 150: Data Intuition and Insight
  + Section 1.1: Tidy Data (Type: Data)
  + Sections 6.1.1 and 6.1.2: Google Sheets (Type: Tools)
  
## Class Notes  

### Day 1

[Learning Manifesto](https://datathink.io/my-learning-manifesto-aka-teaching-philosophy/)

Discussion based class

#### Outcomes

* Leave this class with marketable skills.
* Discover the joy of data literacy.
* Learn about the field of data science and data visualization.

#### Work in progress

We just finished the first draft of this class last Friday.

* We expect to have some hiccups along the way.
* Don’t panic! We are all learning together.
* Seth, Cannon, and I are all capable at visualization, but we will be learning Tableau with you.


[Implement what you learned](https://www.youtube.com/embed/kO8x8eoU3L4?rel=0&start=0)

Tab out your sheets


