---
title: "Case Study 2"
subtitle: "Class Meeting"
---

## Objective 
Students discover team collaboration, understand collecting data vs. data summaries and reporting results using visualization with 4 hours of class time and 6-8 hours of beyond class time.

### Topics Covered

* How data are recorded and stored
* The difference between summary variables, measured variables, and derived variables
* The key summary variables of mean, median, quartiles, and standard deviation
* Basic data visualization reporting

## Readings

### Day 3

* Read Good Charts (Type: Visualization)
  + Chapter 3: Two questions to four types
* Read CSE 150: Data Intuition and Insight
  + Section 1.3.1: Measures of Center (Type: Statistics)
  + Section 6.2: Tableau Registration and Getting Started (Type: Tools)
  
### Day 4

* Read Good Charts (Type: Visualization)
  + Chapter 4: Better Charts in a couple of hours (pg. 73-86)
* Read CSE 150: Data Intuition and Insight
  + Section 1.3.2: Measures of Spread (Type: Statistics)
  
### Day 5  

* Read Good Charts (Type: Visualization)
  + Chapter 4: Better Charts in a couple of hours (pg. 87-108)
* Read CSE 150: Data Intuition and Insight
  + Section 1.4: Graphical Summaries (Type: Statistics)
  
### Day 6  

* Read CSE 150: Data Intuition and Insight
  + Section 1.5: Data vs. Summaries (Type: Data)
  + Section 6.2.3 Tableau Introduction depth (Type: Tools)
  
## Class Notes  