---
title: "Case Study 5"
subtitle: "Class Meeting"
---

## Objective 

Students discover how to move their visualizations and data beyond descriptions to make inferential statements using statistics. They will be introduced to how to compare proportion estimates from two groups to see if they are different (test of two proportions).  In addition, they will be introduced to methods for comparing two categorical measures to test for a relationship (Chi-Square test of independence)

## Topics Covered

* Hypothesis testing and its use in statistical inference.
* How to compare two proportions to see if the populations are different.
* How to compare two categorical variables to see if there is a relationship between them.

## Readings

### Day 15

* Read Good Charts (Type: Visualization)
  + Chapter 8: Present to Persuade (pg. 192-208)
* Read CSE 150 Data Intuition and Insight 
  + Section 4.1: Hypothesis Tests (Type: Statistics)

### Day 16

* Read CSE 150 Data Intuition and Insight 
  + Section 4.2: Test for Two Proportions (Type: Statistics)

### Day 17

* Read CSE 150 Data Intuition and Insight
  + Section 4.3: Chi-Squared Test of Independence (Type: Statistics)

### Day 18

* Read CSE 150 Data Intuition and Insight
  + Section 4.4: Chi-Square Goodness of Fit Test (Type: Statistics)
  
## Class Notes  